### ISSUE TITLE
error after install and build

### ISSUE THREAD

**Issue by kozhinas** [aboozaid/react-native-tethering#14]
Unresolved reference: STATUS_NETWORK_SUGGESTIONS_ERROR_RESTRICTED_BY_ADMIN

**Comment by aboozaid** [comment]
Seems like you're using a device which has been restricted to suggest a WiFi Network by the device owner.

**Comment by kozhinas** [comment]
> Seems like you're using a device which has been restricted to suggest a WiFi Network by the device owner.

this error appears on any physical devices and simulators, it happens during app build process, i can't even run it

**Comment by aboozaid** [comment]
Can you please provide which react-native version you use and your gradle version? Also include the full error here

**Comment by kozhinas** [comment]
> Can you please provide which react-native version you use and your gradle version? Also include the full error here


![1233](https://github.com/aboozaid/react-native-tethering/assets/91533857/d4779ee5-5f5a-4d75-9a7f-c800df3d158c)
 "react-native": "0.66.5",
 gradle:4.2.2
 
 Unresolved reference: STATUS_NETWORK_SUGGESTIONS_ERROR_RESTRICTED_BY_ADMIN

**Comment by aboozaid** [comment]
you will need to upgrade your `buildToolsVersion` to 33.0.0 in order to build. this reference can be found in android api 33 and above.

**Comment by kozhinas** [comment]
> you will need to upgrade your `buildToolsVersion` to 33.0.0 in order to build. this reference can be found in android api 33 and above.

apparently I will have to update gradle, as I try to do this, I will write about the results, since simply changing the version did not help me, it builds in the 30th version, can you tell me which version of the gradle do you use?

**Comment by aboozaid** [comment]
You can check the example in the package which uses gradle version 7.3.1

**Comment by kozhinas** [comment]
> You can check the example in the package which uses gradle version 7.3.1


no, there are too many problems to update to the new version, many libraries have the old standard and need to be patched, your solution will not work for me unfortunately, thanks
