### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by matze10000** [aboozaid/react-native-tethering#17]
Nice to see there is movement in the React Native Wifi space. 
I unfortunately have an error with the Android build:
/WifiTethering.kt: (628, 37): Unresolved reference: STATUS_NETWORK_SUGGESTIONS_ERROR_RESTRICTED_BY_ADMIN

**Comment by ohtoyeyejke** [comment]
@matze10000 take a look at this : https://github.com/aboozaid/react-native-tethering/issues/14

**Comment by aboozaid** [comment]
You have to upgrade your gradle version to 7.3.1. check the example btw

**Comment by matze10000** [comment]
Thank you with compileSdkVersion 33 the build ran completely through
