### ISSUE TITLE
connectToNetwork - Connection timeout

### ISSUE THREAD

**Issue by matze10000** [aboozaid/react-native-tethering#19]
The connectToNetwork method returns after the first successful connection, after restarting the app only 'Connection timeout'. Timeout parameter is set to 1000.

**Comment by aboozaid** [comment]
What do you mean by restarting the app? why you want to call `connectToNetwork` if you are already connected to the network?

**Comment by matze10000** [comment]
After closing the app, the connected wifi is disconnected and when restarting the app, there was no reconnection to the wifi, but the 'Connection timeout' error message.
But I had now also noticed that already at the first connection the connection is broken after a few seconds.
I think I need to do more tests with more different Wifi's to be able to better assess.
Sorry for the effort, I would close the issue for now.
