### ISSUE TITLE
Configure Hotspot To Change SSID and Password

### ISSUE THREAD

**Issue by sankethan** [aboozaid/react-native-tethering#20]
Is there any way to **configure** the Hotspot a desired SSID and Password? 

If yes, How?

If not, what are the alternatives? and can we work on the library to make it possible?

**Comment by ohtoyeyejke** [comment]
> Is there any way to **configure** the Hotspot a desired SSID and Password? 
> 
> If yes, How?
> 
> If not, what are the alternatives? and can we work on the library to make it possible?

Starting from android 8 and above you cannot change SSID & Password of a hotspot. If you want a local connection between two devices you could use BLE with Hotspot as ShareIt do just to share these credentials to the other devices without letting the user types them.

Answered by aboozaid on a closed issue where I asked the same thing

**Comment by sankethan** [comment]
I have a data logging device which searches for WiFi with specified SSID and if found Connects to  it using the specified Password. Can you elaborate on how to use `BLE with Hotspot as ShareIt `. 

Thank you

**Comment by aboozaid** [comment]
Is that data logging device support BLE or WiFi Direct? if that device running Android OS you can root it and then create a fixed SSID & Password which people will connect to it using their phones.

**Comment by sankethan** [comment]
It has Bluetooth advertising Capabilities. But the firmware cannot be changed now. It searches for a custom hotspot and sends data over that hotspot to the server. I want to automate the custom hotspot creation part beacuse not all people who use this devices  know how to configure hotspot in their phone settings. I want to make a app which has a button which does this for them. 

any sugesstions?

**Comment by aboozaid** [comment]
You cannot change hotspot settings anymore. If your hardware supports creating a local hotspot you can let people connect to it.

**Comment by sankethan** [comment]
Ok Thanks for the Help
