### ISSUE TITLE
Parameter specified as non-null is null :method kotlin.jvm.internal.inherites.checkNotNull permitter error

### ISSUE THREAD

**Issue by PrudhviBanki** [aboozaid/react-native-tethering#22]
console.log('wifiSSID:', this.state.wifiSSID);
 console.log('password:', this.state.password);
 WifiTethering.connectToNetwork(this.state.wifiSSID, this.state.password, true, 6000)
            .then(() => {
               console.log("Connected successfully!");
            })
            .catch(error => {
               console.error("Error connecting to network:", error);
            });

this will work? facing issue

**Comment by aboozaid** [comment]
Which android version do you use? Device type?

Is it always fail to connect? Are you sure you allow all permissions needed?

**Comment by PrudhviBanki** [comment]
I have solve my issue 
npm link : https://www.npmjs.com/package/react-native-pk-wifi-manager
